In [1]:
from pathlib import Path

import geopandas as gpd
import polars as pl

from h3xplorer import core

In [2]:
data_dir = Path("D:/programming/data/h3xplorer")
census2011_dir = data_dir / "census2011"
census2021_dir = data_dir / "census2021"

In [3]:
c2011_df = pl.read_csv(census2011_dir / "ks404ew_car_or_van_availability_clean.csv")
c2021_df = pl.read_csv(census2021_dir / "rs008_car_or_van_availability_clean.csv")
display(c2011_df, c2021_df)

shape: (34_753, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ 2011      ┆ mnemonic  ┆ All categ ┆ No cars   ┆ … ┆ 2 cars or ┆ 3 cars or ┆ 4 or more ┆ sum of   │
│ super     ┆ ---       ┆ ories:    ┆ or vans   ┆   ┆ vans in   ┆ vans in   ┆ cars or   ┆ all cars │
│ output    ┆ str       ┆ Car or    ┆ in        ┆   ┆ household ┆ household ┆ vans in   ┆ or vans  │
│ area -    ┆           ┆ van ava…  ┆ household ┆   ┆ ---       ┆ ---       ┆ hous…     ┆ in the…  │
│ lower…    ┆           ┆ ---       ┆ ---       ┆   ┆ i64       ┆ i64       ┆ ---       ┆ ---      │
│ ---       ┆           ┆ i64       ┆ i64       ┆   ┆           ┆           ┆ i64       ┆ i64      │
│ str       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ City of   ┆ E01000001 ┆ 876       ┆ 519       ┆ … ┆ 53        ┆ 15        ┆ 4         ┆ 452      │
│ London    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001A      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ City of   ┆ E01000002 ┆ 830       ┆ 481       ┆ … ┆ 38        ┆ 13        ┆ 5         ┆ 441      │
│ London    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001B      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ City of   ┆ E01000003 ┆ 817       ┆ 655       ┆ … ┆ 11        ┆ 2         ┆ 1         ┆ 180      │
│ London    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001C      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ City of   ┆ E01000005 ┆ 467       ┆ 356       ┆ … ┆ 9         ┆ 2         ┆ 0         ┆ 124      │
│ London    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001E      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Barking   ┆ E01000006 ┆ 543       ┆ 186       ┆ … ┆ 87        ┆ 14        ┆ 7         ┆ 496      │
│ and       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Dagenham  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 016A      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Cardiff   ┆ W01001954 ┆ 637       ┆ 73        ┆ … ┆ 235       ┆ 60        ┆ 20        ┆ 1001     │
│ 006F      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Swansea   ┆ W01001955 ┆ 1153      ┆ 863       ┆ … ┆ 24        ┆ 3         ┆ 1         ┆ 329      │
│ 025F      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Swansea   ┆ W01001956 ┆ 803       ┆ 105       ┆ … ┆ 220       ┆ 63        ┆ 26        ┆ 1127     │
│ 023E      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Swansea   ┆ W01001957 ┆ 411       ┆ 173       ┆ … ┆ 57        ┆ 1         ┆ 5         ┆ 312      │
│ 025G      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Swansea   ┆ W01001958 ┆ 836       ┆ 330       ┆ … ┆ 117       ┆ 13        ┆ 3         ┆ 658      │
│ 025H      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (35_672, 5)
┌────────────────────────────┬───────────┬───────┬────────────────────┬────────────────────────────┐
│ 2021 super output area -   ┆ mnemonic  ┆ Total ┆ No cars or vans in ┆ 1 or more cars or vans in  │
│ lower…                     ┆ ---       ┆ ---   ┆ household          ┆ hous…                      │
│ ---                        ┆ str       ┆ i64   ┆ ---                ┆ ---                        │
│ str                        ┆           ┆       ┆ i64                ┆ i64                        │
╞════════════════════════════╪═══════════╪═══════╪════════════════════╪════════════════════════════╡
│ Hartlepool 001A            ┆ E01011954 ┆ 965   ┆ 305                ┆ 660                        │
│ Hartlepool 001B            ┆ E01011969 ┆ 596   ┆ 82                 ┆ 514                        │
│ Hartlepool 001C            ┆ E01011970 ┆ 485   ┆ 48                 ┆ 437                        │
│ Hartlepool 001D            ┆ E01011971 ┆ 516   ┆ 28                 ┆ 488                        │
│ Hartlepool 001F            ┆ E01033465 ┆ 742   ┆ 57                 ┆ 685                        │
│ …                          ┆ …         ┆ …     ┆ …                  ┆ …                          │
│ Merthyr Tydfil 008B        ┆ W01001300 ┆ 694   ┆ 268                ┆ 426                        │
│ Merthyr Tydfil 008C        ┆ W01001301 ┆ 771   ┆ 317                ┆ 454                        │
│ Merthyr Tydfil 008D        ┆ W01001308 ┆ 485   ┆ 174                ┆ 311                        │
│ Merthyr Tydfil 008E        ┆ W01001309 ┆ 516   ┆ 142                ┆ 374                        │
│ Merthyr Tydfil 008F        ┆ W01001898 ┆ 644   ┆ 126                ┆ 518                        │
└────────────────────────────┴───────────┴───────┴────────────────────┴────────────────────────────┘

In [4]:
c2011_df = c2011_df.with_columns(
    (
        pl.col("All categories: Car or van availability") - pl.col("No cars or vans in household")
    ).alias("1 or more cars or vans in household")
)

In [5]:
display(c2011_df.sum(), c2021_df.sum())

shape: (1, 10)
┌────────┬──────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ 2011   ┆ mnemonic ┆ All catego ┆ No cars or ┆ … ┆ 3 cars or  ┆ 4 or more ┆ sum of    ┆ 1 or more │
│ super  ┆ ---      ┆ ries: Car  ┆ vans in    ┆   ┆ vans in    ┆ cars or   ┆ all cars  ┆ cars or   │
│ output ┆ str      ┆ or van     ┆ household  ┆   ┆ household  ┆ vans in   ┆ or vans   ┆ vans in   │
│ area - ┆          ┆ ava…       ┆ ---        ┆   ┆ ---        ┆ hous…     ┆ in the…   ┆ hous…     │
│ lower… ┆          ┆ ---        ┆ i64        ┆   ┆ i64        ┆ ---       ┆ ---       ┆ ---       │
│ ---    ┆          ┆ i64        ┆            ┆   ┆            ┆ i64       ┆ i64       ┆ i64       │
│ str    ┆          ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
╞════════╪══════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ null   ┆ null     ┆ 23366044   ┆ 5989770    ┆ … ┆ 1283780    ┆ 453190    ┆ 27294656  ┆ 17376274  │
└────────┴──────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

shape: (1, 5)
┌───────────────────────────┬──────────┬──────────┬────────────────────┬───────────────────────────┐
│ 2021 super output area -  ┆ mnemonic ┆ Total    ┆ No cars or vans in ┆ 1 or more cars or vans in │
│ lower…                    ┆ ---      ┆ ---      ┆ household          ┆ hous…                     │
│ ---                       ┆ str      ┆ i64      ┆ ---                ┆ ---                       │
│ str                       ┆          ┆          ┆ i64                ┆ i64                       │
╞═══════════════════════════╪══════════╪══════════╪════════════════════╪═══════════════════════════╡
│ null                      ┆ null     ┆ 24783094 ┆ 5777874            ┆ 19005220                  │
└───────────────────────────┴──────────┴──────────┴────────────────────┴───────────────────────────┘

In [6]:
c2011_points = gpd.read_file(census2011_dir / "lsoa_centroids_pop_weighted.gpkg")
c2021_points = gpd.read_file(census2021_dir / "lsoa_centroids_pop_weighted.gpkg")
display(c2011_points, c2021_points)

,lsoa11cd,lsoa11nm,GlobalID,geometry
0,E01012007,Middlesbrough 012A,{AFA2ED09-F2DE-46C7-9AF5-A6CF144E0089},POINT (449119.175 517017.509)
1,E01012085,Middlesbrough 010D,{DA432A35-D526-4A6E-BEB1-0D602E60B6CD},POINT (451722.55 517577.735)
2,E01012005,Hartlepool 014G,{3CB4CB22-A4AF-488B-B6E1-7A0F282D543C},POINT (448657.056 533984.633)
3,E01012084,Middlesbrough 010C,{8D0D433D-5685-43BA-AE26-F11C176C799E},POINT (451977.348 517832.468)
4,E01012002,Hartlepool 006D,{8123E0DE-A96A-4FA4-BBEC-99D297EF9C96},POINT (449565.447 533268.699)
...,...,...,...,...
34748,W01000417,Wrexham 020D,{B93C4447-531D-4B4B-B4D9-7726AB26C07D},POINT (337219.445 357361.542)
34749,W01000499,Powys 003B,{05C30EBE-896E-440D-BFF8-45A38F6CEA8F},POINT (322960.506 307752.216)
34750,W01001833,Cardiff 033D,{03DF1F40-E27C-44A3-846A-B36A5C4FE5AF},POINT (319631.643 177494.299)
34751,W01000779,Swansea 012D,{95AC54B8-2F2D-4B46-83C8-BCF85CF18A0D},POINT (258678.294 196070.614)
34752,W01001047,Bridgend 018D,{212AE2AD-5BB3-4488-8AA6-2D18868AEEA2},POINT (281607.922 177322.904)

,LSOA21CD,GlobalID,geometry
0,E01000001,{38AD8FE8-682A-4533-B51A-16C9CA366294},POINT (532181.764 181792.282)
1,E01018945,{0681C038-F7DD-4A2E-83C1-C8D3B32443F6},POINT (202699.421 65668.022)
2,E01000120,{E5FFC70B-0E24-40A9-AFE8-13DA1EC4032E},POINT (528823.572 194238.047)
3,E01031487,{17C7F13F-1A6A-45C5-A5CC-2C50E725C799},POINT (486282.408 106971.914)
4,E01021013,{F55E8508-E975-4025-896C-A270DE41FC79},POINT (583256.523 111412.976)
...,...,...,...
35667,E01023639,{ACC5933E-F958-4D5E-9D7C-BF80D3B3A8E4},POINT (522759.602 231115)
35668,E01035505,{8CD1A7C3-774B-445D-9586-0D3CD2EC8816},POINT (455489.769 339157.694)
35669,E01012119,{3E2E1865-4904-4BAE-BE77-16DC09DA2363},POINT (460894.709 516424.309)
35670,E01026708,{02DFB6DA-68F7-4B30-A2AB-CA024FCF491E},POINT (564232.341 323205.502)
35671,E01026019,{AEE5860C-33AD-4770-AEBC-C99846EBCC66},POINT (530842.028 338534.461)

In [7]:
def _get_points(gdf: gpd.GeoDataFrame, retain_cols: list[str]) -> pl.DataFrame:
    return pl.DataFrame(
        {"x": gdf.geometry.x, "y": gdf.geometry.y} | {col: gdf.loc[:, col] for col in retain_cols}
    )


c2011_xys = _get_points(c2011_points, ["lsoa11cd"])
c2021_xys = _get_points(c2021_points, ["LSOA21CD"])
display(c2011_xys, c2021_xys)

shape: (34_753, 3)
┌────────────┬────────────┬───────────┐
│ x          ┆ y          ┆ lsoa11cd  │
│ ---        ┆ ---        ┆ ---       │
│ f64        ┆ f64        ┆ str       │
╞════════════╪════════════╪═══════════╡
│ 449119.175 ┆ 517017.509 ┆ E01012007 │
│ 451722.55  ┆ 517577.735 ┆ E01012085 │
│ 448657.056 ┆ 533984.633 ┆ E01012005 │
│ 451977.348 ┆ 517832.468 ┆ E01012084 │
│ 449565.447 ┆ 533268.699 ┆ E01012002 │
│ …          ┆ …          ┆ …         │
│ 337219.445 ┆ 357361.542 ┆ W01000417 │
│ 322960.506 ┆ 307752.216 ┆ W01000499 │
│ 319631.643 ┆ 177494.299 ┆ W01001833 │
│ 258678.294 ┆ 196070.614 ┆ W01000779 │
│ 281607.922 ┆ 177322.904 ┆ W01001047 │
└────────────┴────────────┴───────────┘

shape: (35_672, 3)
┌─────────────┬─────────────┬───────────┐
│ x           ┆ y           ┆ LSOA21CD  │
│ ---         ┆ ---         ┆ ---       │
│ f64         ┆ f64         ┆ str       │
╞═════════════╪═════════════╪═══════════╡
│ 532181.7642 ┆ 181792.2818 ┆ E01000001 │
│ 202699.4208 ┆ 65668.0221  ┆ E01018945 │
│ 528823.5718 ┆ 194238.0466 ┆ E01000120 │
│ 486282.4085 ┆ 106971.9143 ┆ E01031487 │
│ 583256.5228 ┆ 111412.9755 ┆ E01021013 │
│ …           ┆ …           ┆ …         │
│ 522759.6016 ┆ 231115.0    ┆ E01023639 │
│ 455489.7686 ┆ 339157.6943 ┆ E01035505 │
│ 460894.7087 ┆ 516424.309  ┆ E01012119 │
│ 564232.3414 ┆ 323205.5021 ┆ E01026708 │
│ 530842.028  ┆ 338534.4605 ┆ E01026019 │
└─────────────┴─────────────┴───────────┘

In [8]:
c2011_data = (
    c2011_df.join(c2011_xys, left_on="mnemonic", right_on="lsoa11cd")
    .select(
        "x",
        "y",
        no_car="No cars or vans in household",
        has_car="1 or more cars or vans in household",
        total="All categories: Car or van availability",
    )
    .with_columns((pl.col("has_car") / pl.col("total")).alias("percent_with_car"))
)
c2021_data = (
    c2021_df.join(c2021_xys, left_on="mnemonic", right_on="LSOA21CD")
    .select(
        "x",
        "y",
        no_car="No cars or vans in household",
        has_car="1 or more cars or vans in household",
        total="Total",
    )
    .with_columns((pl.col("has_car") / pl.col("total")).alias("percent_with_car"))
)
display(c2011_data, c2021_data)

shape: (34_753, 6)
┌────────────┬────────────┬────────┬─────────┬───────┬──────────────────┐
│ x          ┆ y          ┆ no_car ┆ has_car ┆ total ┆ percent_with_car │
│ ---        ┆ ---        ┆ ---    ┆ ---     ┆ ---   ┆ ---              │
│ f64        ┆ f64        ┆ i64    ┆ i64     ┆ i64   ┆ f64              │
╞════════════╪════════════╪════════╪═════════╪═══════╪══════════════════╡
│ 449119.175 ┆ 517017.509 ┆ 128    ┆ 537     ┆ 665   ┆ 0.807519         │
│ 451722.55  ┆ 517577.735 ┆ 300    ┆ 284     ┆ 584   ┆ 0.486301         │
│ 448657.056 ┆ 533984.633 ┆ 35     ┆ 682     ┆ 717   ┆ 0.951185         │
│ 451977.348 ┆ 517832.468 ┆ 422    ┆ 276     ┆ 698   ┆ 0.395415         │
│ 449565.447 ┆ 533268.699 ┆ 179    ┆ 428     ┆ 607   ┆ 0.705107         │
│ …          ┆ …          ┆ …      ┆ …       ┆ …     ┆ …                │
│ 337219.445 ┆ 357361.542 ┆ 29     ┆ 611     ┆ 640   ┆ 0.9546875        │
│ 322960.506 ┆ 307752.216 ┆ 182    ┆ 373     ┆ 555   ┆ 0.672072         │
│ 319631.643 ┆ 177494.299 ┆ 260    ┆ 456     ┆ 716   ┆ 0.636872         │
│ 258678.294 ┆ 196070.614 ┆ 109    ┆ 488     ┆ 597   ┆ 0.81742          │
│ 281607.922 ┆ 177322.904 ┆ 148    ┆ 609     ┆ 757   ┆ 0.804491         │
└────────────┴────────────┴────────┴─────────┴───────┴──────────────────┘

shape: (35_672, 6)
┌─────────────┬─────────────┬────────┬─────────┬───────┬──────────────────┐
│ x           ┆ y           ┆ no_car ┆ has_car ┆ total ┆ percent_with_car │
│ ---         ┆ ---         ┆ ---    ┆ ---     ┆ ---   ┆ ---              │
│ f64         ┆ f64         ┆ i64    ┆ i64     ┆ i64   ┆ f64              │
╞═════════════╪═════════════╪════════╪═════════╪═══════╪══════════════════╡
│ 532181.7642 ┆ 181792.2818 ┆ 553    ┆ 282     ┆ 835   ┆ 0.337725         │
│ 202699.4208 ┆ 65668.0221  ┆ 32     ┆ 526     ┆ 558   ┆ 0.942652         │
│ 528823.5718 ┆ 194238.0466 ┆ 50     ┆ 443     ┆ 493   ┆ 0.89858          │
│ 486282.4085 ┆ 106971.9143 ┆ 78     ┆ 603     ┆ 681   ┆ 0.885463         │
│ 583256.5228 ┆ 111412.9755 ┆ 147    ┆ 585     ┆ 732   ┆ 0.79918          │
│ …           ┆ …           ┆ …      ┆ …       ┆ …     ┆ …                │
│ 522759.6016 ┆ 231115.0    ┆ 40     ┆ 514     ┆ 554   ┆ 0.927798         │
│ 455489.7686 ┆ 339157.6943 ┆ 422    ┆ 552     ┆ 974   ┆ 0.566735         │
│ 460894.7087 ┆ 516424.309  ┆ 191    ┆ 698     ┆ 889   ┆ 0.785152         │
│ 564232.3414 ┆ 323205.5021 ┆ 38     ┆ 554     ┆ 592   ┆ 0.935811         │
│ 530842.028  ┆ 338534.4605 ┆ 217    ┆ 937     ┆ 1154  ┆ 0.811958         │
└─────────────┴─────────────┴────────┴─────────┴───────┴──────────────────┘

In [9]:
hex_size = 6
display(
    core.xy_plot(c2011_data, "x", "y", 27700, hex_size, "total", "sum"),
    core.xy_plot(c2021_data, "x", "y", 27700, hex_size, "total", "sum"),
)

2025-10-12 16:09:09,682 [INFO] Converting points to EPSG:4326
2025-10-12 16:09:09,814 [INFO] Point conversion complete
2025-10-12 16:09:09,819 [INFO] Getting hexagon references
Converting points to h3 references: 100%|██████████| 34753/34753 [00:00<00:00, 738591.10it/s]
2025-10-12 16:09:09,875 [INFO] Hexagon references retrieved
2025-10-12 16:09:09,878 [INFO] Creating hexagon polygons table
Converting h3 references to polygons: 100%|██████████| 3594/3594 [00:00<00:00, 119719.24it/s]
2025-10-12 16:09:10,032 [INFO] aggregating data input to spatial areas
2025-10-12 16:09:10,102 [INFO] Converting points to EPSG:4326
2025-10-12 16:09:10,225 [INFO] Point conversion complete
2025-10-12 16:09:10,229 [INFO] Getting hexagon references
Converting points to h3 references: 100%|██████████| 35672/35672 [00:00<00:00, 744607.57it/s]
2025-10-12 16:09:10,280 [INFO] Hexagon references retrieved
2025-10-12 16:09:10,283 [INFO] Creating hexagon polygons table
Converting h3 references to polygons: 100%|██████████| 3590/3590 [00:00<00:00, 122888.69it/s]
2025-10-12 16:09:10,422 [INFO] aggregating data input to spatial areas

Map(basemap_style=<CartoBasemap.DarkMatter: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json'…

Map(basemap_style=<CartoBasemap.DarkMatter: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json'…

In [11]:
display(
    core.xy_plot(c2011_data, "x", "y", 27700, hex_size, "percent_with_car", "mean"),
    core.xy_plot(c2021_data, "x", "y", 27700, hex_size, "percent_with_car", "mean"),
)

2025-10-12 16:09:20,882 [INFO] Converting points to EPSG:4326
2025-10-12 16:09:20,972 [INFO] Point conversion complete
2025-10-12 16:09:20,977 [INFO] Getting hexagon references
Converting points to h3 references: 100%|██████████| 34753/34753 [00:00<00:00, 752869.90it/s]
2025-10-12 16:09:21,026 [INFO] Hexagon references retrieved
2025-10-12 16:09:21,029 [INFO] Creating hexagon polygons table
Converting h3 references to polygons: 100%|██████████| 3594/3594 [00:00<00:00, 76843.19it/s]
2025-10-12 16:09:21,190 [INFO] aggregating data input to spatial areas
2025-10-12 16:09:21,238 [INFO] Converting points to EPSG:4326
2025-10-12 16:09:21,388 [INFO] Point conversion complete
2025-10-12 16:09:21,392 [INFO] Getting hexagon references
Converting points to h3 references: 100%|██████████| 35672/35672 [00:00<00:00, 777771.95it/s]
2025-10-12 16:09:21,441 [INFO] Hexagon references retrieved
2025-10-12 16:09:21,445 [INFO] Creating hexagon polygons table
Converting h3 references to polygons: 100%|██████████| 3590/3590 [00:00<00:00, 114950.16it/s]
2025-10-12 16:09:21,585 [INFO] aggregating data input to spatial areas

Map(basemap_style=<CartoBasemap.DarkMatter: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json'…

Map(basemap_style=<CartoBasemap.DarkMatter: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json'…